### ISSUE TITLE
License & F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [GittyMac/MoClock#1]
Hi,

What's the license of this project?

If it's a FLOSS license, would it be possible for you to add it to [F-Droid](https://f-droid.org/)?

**Comment by GittyMac** [comment]
I added a submission issue to the F-Droid repository and added a license. Will close when I get a final decision.

**Comment by Poussinou** [comment]
https://gitlab.com/fdroid/rfp/issues/1126
