### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [GittyMac/MoClock#3]
When i click on Timer, i see Set Timer in white writing. that means white writing on a white background. if you look long enough you can see that too. i think you should change that.
left (clock) is black on white, you can see that well. and right (stopwatch) is also black on white, you can see that well. but timer -white on white- that is really difficult.

![moclock](https://user-images.githubusercontent.com/61406324/78997356-b56d7c80-7b46-11ea-8737-4885ad8d11d3.jpg)

**Comment by GittyMac** [comment]
I noticed that after releasing v2.0, will release an update with the corrected color.

**Comment by GittyMac** [comment]
This has been fixed as of v2.1.
