### ISSUE TITLE
detail view MoClock

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [GittyMac/MoClock#4]
Izzy has asked me to write this to you because you need to change it so that it is displayed correctly in his repo and the following updates can be applied.
and i hope you understand me that you can change this. and please don't close this issue until izzy shows it correctly in his repo.
but thanks for correcting this with my issue. not every programmer cares about his own software.

so it all started with [Timer #3](https://github.com/GittyMac/MoClock/issues/3) 

(THIS was version 2.0) where the SET TIMER was white writing on a white background.

you @GittyMac replied as you can see he cares. and in his second reply you @GittyMac wrote - This has been fixed as of v2.1. - then you @GittyMac closed the issue. 

so the latest app has version 2.1.

on this page [MoClock releases](https://github.com/GittyMac/MoClock/releases)

the old version is below, version 2.0 and above as newest app the version 2.1 (fixed "Set Timer")
in the attachment is still the moclock detail view. it's in german, but i think you already understand what i mean - i've explained it too. and if not, please ask.
![moclockdetail](https://user-images.githubusercontent.com/61406324/79544451-5603f500-808f-11ea-95bf-7fc8790e5cdb.jpg)

here you see both versions with v2.0. but the older one is version 2.0 and the newer one is version 2.1 and on top there should be NEW IN VERSION V2.1

I hope you understood me so that you could change that. that's it..

**Comment by GittyMac** [comment]
Oh, I forgot to change the version number in Android Studio, I heavily apologize for that.

**Comment by mondlicht-und-sterne** [comment]
thank you . now you can close the  issue ;)
